### ISSUE TITLE
Write up about what we understood on the two sides of the argument

### ISSUE THREAD

**Issue by aacharya23** [sds-capstone/womenatthetable#44]
This will be complete when we all put together a write up

**Comment by ekornberg** [comment]
https://www.equivant.com/risk-scores-the-not-so-secret-recipe/

**Comment by ekornberg** [comment]
https://www.michigan.gov/documents/corrections/Timothy_Brenne_Ph.D.__Meaning_and_Treatment_Implications_of_COMPA_Core_Scales_297495_7.pdf
