### ISSUE TITLE
Identify 3 fairness metrics for deeper dive

### ISSUE THREAD

**Issue by enesmith** [sds-capstone/womenatthetable#82]
This issue will be complete when we decide on three different fairness metrics to evaluate the data and debasing approaches. We should be able to explain what they each mean in the context of compas and recidivism and how they define fairness.

**Comment by ekornberg** [comment]
https://www.sciencedirect.com/science/article/pii/S0306457321001369

**Comment by ekornberg** [comment]
https://towardsdatascience.com/fairness-metrics-wont-save-you-from-stereotyping-27127e220cac#:~:text=Calibration%20A%20calibration%20test%20for%20fairness%20examines%20whether,to%20create%20decile%20groups%20from%20model%20probability%20outputs.

**Comment by ekornberg** [comment]
https://arxiv.org/abs/1807.00787
