### ISSUE TITLE
Identify who uses COMPAS and for what

### ISSUE THREAD

**Issue by enesmith** [sds-capstone/womenatthetable#83]
This will be completed when we can identify 2 or 3 U.S. institutions/organizations that use the Compas algorithm and how. We will add this information as background and context in the intro of our paper.

**Comment by ekornberg** [comment]
https://www.courtinnovation.org/sites/default/files/documents/COMPAS%20Validation%20Study.pdf

**Comment by ekornberg** [comment]
https://hdsr.mitpress.mit.edu/pub/hzwo7ax4/release/4

**Comment by ekornberg** [comment]
https://hdsr.mitpress.mit.edu/pub/7z10o269/release/4

**Comment by eukim89** [comment]
We have added this section to the paper; now, we just have to add it to the write up for Sofia.
