### ISSUE TITLE
Thursday class discussion preparation

### ISSUE THREAD

**Issue by ekornberg** [sds-capstone/womenatthetable#91]
discussion questions? 
introductory explanation
explore data?
our plots?
explain project?

**Comment by ekornberg** [comment]
https://towardsdatascience.com/compas-case-study-fairness-of-a-machine-learning-model-f0f804108751

**Comment by beanumber** [comment]
Great find @ekornberg !! I'm definitely going to add the Rudin piece to the mix for next year. 

I've only read the abstract, but one thing I don't hear Rudin talking about is the fact that criminal history is itself a source of bias.
